"""
Unit tests for Config Generator functionality.

Tests the ConfigGenerator class and its ability to generate curated
configuration files based on selected systems and applications.
"""

import pytest
import yaml
from unittest.mock import Mock, patch
from parslbox.utils.config_generator import ConfigGenerator, get_builtin_apps


class TestConfigGenerator:
    """Test cases for the ConfigGenerator class."""
    
    def test_init(self):
        """Test ConfigGenerator initialization."""
        systems = ["polaris", "sophia"]
        apps = ["lammps", "python"]
        
        generator = ConfigGenerator(systems, apps)
        
        assert generator.systems == systems
        assert generator.apps == apps
    
    def test_generate_basic_structure(self):
        """Test that generated config has basic YAML structure."""
        generator = ConfigGenerator(["polaris"], ["python"])
        config_str = generator.generate()
        
        # Should be valid YAML
        config = yaml.safe_load(config_str)
        
        # Should have main sections
        assert "schedulers" in config
        assert "polaris" in config
        assert "custom_apps" in config
        assert "python" in config
    
    def test_generate_header(self):
        """Test header generation."""
        generator = ConfigGenerator(["polaris", "sophia"], ["lammps", "vasp"])
        header = generator._generate_header()
        
        assert "ParslBox Configuration" in header
        assert "polaris, sophia" in header
        assert "lammps, vasp" in header
        assert "Auto-generated by: pbx config" in header
    
    def test_generate_schedulers_pbs_only(self):
        """Test scheduler generation for PBS-only systems."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], ["python"])
            schedulers = generator._generate_schedulers()
            
            assert "pbs:" in schedulers
            assert "#PBS" in schedulers
            assert "slurm:" not in schedulers
            assert "#SBATCH" not in schedulers
    
    def test_generate_schedulers_slurm_only(self):
        """Test scheduler generation for SLURM-only systems."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "slurm"
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["sophia"], ["python"])
            schedulers = generator._generate_schedulers()
            
            assert "slurm:" in schedulers
            assert "#SBATCH" in schedulers
            assert "pbs:" not in schedulers
            assert "#PBS" not in schedulers
    
    def test_generate_schedulers_both(self):
        """Test scheduler generation for mixed PBS/SLURM systems."""
        def mock_get_sys(name):
            mock = Mock()
            mock.SCHEDULER = "pbs" if name == "polaris" else "slurm"
            return mock
        
        with patch('parslbox.utils.config_generator.get_system_config', side_effect=mock_get_sys):
            generator = ConfigGenerator(["polaris", "sophia"], ["python"])
            schedulers = generator._generate_schedulers()
            
            assert "pbs:" in schedulers
            assert "#PBS" in schedulers
            assert "slurm:" in schedulers
            assert "#SBATCH" in schedulers
    
    def test_generate_systems_single(self):
        """Test system configuration generation for single system."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.get_default_mpi_config_yaml.return_value = {
                "backend": "mpich",
                "use_gpu_wrapper": True,
                "cpu_bind_method": "depth"
            }
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], ["python"])
            systems = generator._generate_systems()

            assert "polaris:" in systems
            assert "pbx_python_env_setup:" in systems
            assert "sched_opts" in systems
            assert "mpi:" in systems
            assert "backend: mpich" in systems
            assert "use_gpu_wrapper: true" in systems
            assert "cpu_bind_method: depth" in systems
    
    def test_generate_systems_sched_opts_pbs(self):
        """Test that PBS systems get PBS sched_opts placeholder."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "mpich"}
            mock_get_sys.return_value = mock_sys

            generator = ConfigGenerator(["polaris"], ["python"])
            systems = generator._generate_systems()

            assert "# sched_opts: |" in systems
            assert "#PBS -l filesystems=home:eagle" in systems
            assert "#PBS -l place=scatter" in systems
            assert "#SBATCH" not in systems

    def test_generate_systems_sched_opts_slurm(self):
        """Test that SLURM systems get SLURM sched_opts placeholder."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "slurm"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "openmpi"}
            mock_get_sys.return_value = mock_sys

            generator = ConfigGenerator(["sophia"], ["python"])
            systems = generator._generate_systems()

            assert "# sched_opts: |" in systems
            assert "#SBATCH --mem=128G" in systems
            assert "#SBATCH --gres=gpu:4" in systems
            assert "#PBS" not in systems

    def test_generate_systems_multiple(self):
        """Test system configuration generation for multiple systems."""
        def mock_get_sys(name):
            mock = Mock()
            if name == "polaris":
                mock.get_default_mpi_config_yaml.return_value = {
                    "backend": "mpich",
                    "use_gpu_wrapper": True
                }
            else:  # sophia
                mock.get_default_mpi_config_yaml.return_value = {
                    "backend": "openmpi",
                    "use_short_hostnames": True
                }
            return mock
        
        with patch('parslbox.utils.config_generator.get_system_config', side_effect=mock_get_sys):
            generator = ConfigGenerator(["polaris", "sophia"], ["python"])
            systems = generator._generate_systems()
            
            assert "polaris:" in systems
            assert "sophia:" in systems
            assert "backend: mpich" in systems
            assert "backend: openmpi" in systems
            assert "use_gpu_wrapper: true" in systems
            assert "use_short_hostnames: true" in systems
    
    def test_format_mpi_config_minimal(self):
        """Test MPI config formatting with minimal options."""
        generator = ConfigGenerator(["polaris"], ["python"])
        
        mpi_config = {"backend": "openmpi"}
        formatted = generator._format_mpi_config(mpi_config)
        
        assert "backend: openmpi" in formatted
        assert "# use_gpu_wrapper: false" in formatted
        assert "# cpu_bind_method: none" in formatted
    
    def test_format_mpi_config_full(self):
        """Test MPI config formatting with all options."""
        generator = ConfigGenerator(["polaris"], ["python"])
        
        mpi_config = {
            "backend": "mpich",
            "use_gpu_wrapper": True,
            "use_hostlist": True,
            "use_short_hostnames": True,
            "cpu_bind_method": "depth",
            "add": ["--verbose"],
            "disable": ["--bind-to"]
        }
        formatted = generator._format_mpi_config(mpi_config)
        
        assert "backend: mpich" in formatted
        assert "use_gpu_wrapper: true" in formatted
        assert "use_hostlist: true" in formatted
        assert "use_short_hostnames: true" in formatted
        assert "cpu_bind_method: depth" in formatted
        assert "add: ['--verbose']" in formatted
        assert "disable: ['--bind-to']" in formatted
    
    def test_format_mpi_config_with_comments(self):
        """Test that MPI config includes helpful comments."""
        generator = ConfigGenerator(["polaris"], ["python"])
        
        mpi_config = {
            "backend": "mpich",
            "use_gpu_wrapper": True,
            "cpu_bind_method": "depth"
        }
        formatted = generator._format_mpi_config(mpi_config)
        
        # Should include comments explaining options
        assert "# Generate per-rank GPU assignment wrapper" in formatted
        assert "# Options: none, rankfile, list, depth" in formatted
    
    def test_generate_custom_apps_section(self):
        """Test custom apps section generation."""
        generator = ConfigGenerator(["polaris"], ["python"])
        custom_apps = generator._generate_custom_apps_section()

        assert "Custom Application Registration" in custom_apps
        assert "custom_apps: {}" in custom_apps
        assert "How it works:" in custom_apps
        assert "Two methods are supported:" in custom_apps
        assert "module:" in custom_apps
        assert "class:" in custom_apps
    
    def test_generate_apps_python(self):
        """Test app configuration generation for Python."""
        generator = ConfigGenerator(["polaris"], ["python"])
        apps = generator._generate_apps()
        
        assert "python:" in apps
        assert "polaris:" in apps
        assert "Python app uses the Python interpreter" in apps
        assert "environment_setup:" in apps
        # Python should NOT have executable_path
        assert 'executable_path: "/path/to/your/python/executable' not in apps
    
    def test_generate_apps_lammps(self):
        """Test app configuration generation for LAMMPS."""
        generator = ConfigGenerator(["polaris"], ["lammps"])
        apps = generator._generate_apps()
        
        assert "lammps:" in apps
        assert "polaris:" in apps
        assert 'executable_path: "/path/to/your/lammps/executable/on/polaris"' in apps
        assert "environment_setup:" in apps
    
    def test_generate_apps_multiple_systems(self):
        """Test app configuration for multiple systems."""
        generator = ConfigGenerator(["polaris", "sophia"], ["lammps"])
        apps = generator._generate_apps()
        
        assert "lammps:" in apps
        assert "polaris:" in apps
        assert "sophia:" in apps
        assert 'executable/on/polaris"' in apps
        assert 'executable/on/sophia"' in apps
    
    def test_generate_apps_multiple_apps(self):
        """Test configuration for multiple apps."""
        generator = ConfigGenerator(["polaris"], ["lammps", "vasp", "python"])
        apps = generator._generate_apps()
        
        assert "lammps:" in apps
        assert "vasp:" in apps
        assert "python:" in apps
    
    def test_generate_example_app_template(self):
        """Test example app template generation."""
        generator = ConfigGenerator(["polaris"], ["python"])
        template = generator._generate_example_app_template()
        
        assert "Example APP Template" in template
        assert "app_name:" in template
        assert "system_name:" in template
        assert "executable_path:" in template
        assert "environment_setup:" in template
        assert "module purge" in template
        assert "Optional: Override system MPI settings" in template
    
    def test_generate_footer(self):
        """Test footer generation contains full MPI reference."""
        generator = ConfigGenerator(["polaris"], ["python"])
        footer = generator._generate_footer()

        assert "MPI Configuration" in footer
        assert "MPI Configuration Options:" in footer
        assert "backend: openmpi | mpich | srun" in footer
        assert "cpu_bind_method:" in footer
        assert "CPU Binding Methods:" in footer
        assert "Template Variables" in footer
        assert "{total_ranks}" in footer
        assert "{hostlist}" in footer
        assert "{rankfile_path}" in footer
    
    def test_sched_opts_section_present(self):
        """Test that generated config includes sched_opts documentation."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "mpich"}
            mock_get_sys.return_value = mock_sys

            generator = ConfigGenerator(["polaris"], ["python"])
            config_str = generator.generate()

            assert "Scheduler Options (sched_opts)" in config_str
            assert "three-layer override chain" in config_str
            assert "--sched-opts" in config_str

    def test_mpi_config_notes_in_footer(self):
        """Test that full MPI reference block appears in generated config."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "mpich"}
            mock_get_sys.return_value = mock_sys

            generator = ConfigGenerator(["polaris"], ["python"])
            config_str = generator.generate()

            assert "MPI Configuration" in config_str
            assert "CPU Binding Methods:" in config_str
            assert "rankfile  - Precise per-rank CPU binding" in config_str
            assert "Template Variables" in config_str
            assert "{total_ranks}" in config_str

    def test_full_config_is_valid_yaml(self):
        """Test that full generated config is valid YAML."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {
                "backend": "mpich",
                "use_gpu_wrapper": True
            }
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], ["lammps", "python"])
            config_str = generator.generate()
            
            # Should parse as valid YAML
            config = yaml.safe_load(config_str)
            
            # Verify structure
            assert isinstance(config, dict)
            assert "schedulers" in config
            assert "polaris" in config
            assert "custom_apps" in config
            assert "lammps" in config
            assert "python" in config
    
    def test_config_has_all_required_sections(self):
        """Test that generated config has all required sections."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "mpich"}
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], ["python"])
            config_str = generator.generate()
            config = yaml.safe_load(config_str)
            
            # Required top-level sections
            assert "schedulers" in config
            assert "custom_apps" in config
            
            # System section
            assert "polaris" in config
            assert "pbx_python_env_setup" in config["polaris"]
            assert "mpi" in config["polaris"]
            
            # App section
            assert "python" in config
            assert "polaris" in config["python"]
    
    def test_empty_systems_list(self):
        """Test handling of empty systems list."""
        generator = ConfigGenerator([], ["python"])
        config_str = generator.generate()
        
        # Should still generate valid config
        config = yaml.safe_load(config_str)
        assert isinstance(config, dict)
        assert "custom_apps" in config
        assert "python" in config
    
    def test_empty_apps_list(self):
        """Test handling of empty apps list."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {"backend": "mpich"}
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], [])
            config_str = generator.generate()
            
            # Should still generate valid config
            config = yaml.safe_load(config_str)
            assert isinstance(config, dict)
            assert "polaris" in config
            assert "custom_apps" in config
    
    def test_invalid_system_handling(self):
        """Test handling of invalid system names."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_get_sys.side_effect = ValueError("Unknown system")
            
            generator = ConfigGenerator(["invalid_system"], ["python"])
            systems = generator._generate_systems()
            
            # Should not crash, just skip invalid system
            assert "invalid_system:" not in systems


class TestGetBuiltinApps:
    """Test cases for get_builtin_apps function."""
    
    def test_get_builtin_apps_returns_list(self):
        """Test that get_builtin_apps returns a list."""
        apps = get_builtin_apps()
        assert isinstance(apps, list)
    
    def test_get_builtin_apps_contains_expected(self):
        """Test that get_builtin_apps contains expected apps."""
        apps = get_builtin_apps()
        
        # Should contain at least these built-in apps
        assert "lammps" in apps
        assert "vasp" in apps
        assert "python" in apps
    
    def test_get_builtin_apps_not_empty(self):
        """Test that get_builtin_apps is not empty."""
        apps = get_builtin_apps()
        assert len(apps) > 0


class TestIntegrationScenarios:
    """Integration test scenarios for real-world use cases."""
    
    def test_polaris_lammps_scenario(self):
        """Test generating config for Polaris + LAMMPS."""
        with patch('parslbox.utils.config_generator.get_system_config') as mock_get_sys:
            mock_sys = Mock()
            mock_sys.SCHEDULER = "pbs"
            mock_sys.get_default_mpi_config_yaml.return_value = {
                "backend": "mpich",
                "use_gpu_wrapper": True,
                "cpu_bind_method": "depth"
            }
            mock_get_sys.return_value = mock_sys
            
            generator = ConfigGenerator(["polaris"], ["lammps"])
            config_str = generator.generate()
            config = yaml.safe_load(config_str)
            
            # Verify PBS scheduler
            assert "pbs" in config["schedulers"]
            
            # Verify Polaris system config
            assert "polaris" in config
            assert config["polaris"]["mpi"]["backend"] == "mpich"
            assert config["polaris"]["mpi"]["use_gpu_wrapper"] is True
            
            # Verify LAMMPS app config
            assert "lammps" in config
            assert "polaris" in config["lammps"]
    
    def test_multi_system_multi_app_scenario(self):
        """Test generating config for multiple systems and apps."""
        def mock_get_sys(name):
            mock = Mock()
            if name == "polaris":
                mock.SCHEDULER = "pbs"
                mock.get_default_mpi_config_yaml.return_value = {
                    "backend": "mpich",
                    "use_gpu_wrapper": True
                }
            else:  # sophia
                mock.SCHEDULER = "slurm"
                mock.get_default_mpi_config_yaml.return_value = {
                    "backend": "openmpi",
                    "use_short_hostnames": True
                }
            return mock
        
        with patch('parslbox.utils.config_generator.get_system_config', side_effect=mock_get_sys):
            generator = ConfigGenerator(
                ["polaris", "sophia"],
                ["lammps", "vasp", "python"]
            )
            config_str = generator.generate()
            config = yaml.safe_load(config_str)
            
            # Both schedulers should be present
            assert "pbs" in config["schedulers"]
            assert "slurm" in config["schedulers"]
            
            # Both systems should be present
            assert "polaris" in config
            assert "sophia" in config
            
            # All apps should be present
            assert "lammps" in config
            assert "vasp" in config
            assert "python" in config
            
            # Each app should have both systems
            for app in ["lammps", "vasp", "python"]:
                assert "polaris" in config[app]
                assert "sophia" in config[app]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
