"""
Config Generator for ParslBox

This module provides functionality to generate curated config.yaml files
based on user-selected systems and applications.

Used by 'pbx config' command to create minimal, relevant configurations.
"""

from typing import List, Dict, Any
from parslbox.system_configs.loader import get_system_config, get_available_systems
from parslbox.apps.app_registry import APP_FACTORY
from parslbox.utils.pbx_config_template import (
    PBS_TEMPLATE, SLURM_TEMPLATE,
    SCHED_OPTS_NOTES, MPI_CONFIG_NOTES,
    CUSTOM_APPS_NOTES, EXAMPLE_APP_TEMPLATE,
)


class ConfigGenerator:
    """
    Generates curated ParslBox configuration files.

    Args:
        systems: List of system names to include
        apps: List of application names to include
    """

    def __init__(self, systems: List[str], apps: List[str]):
        self.systems = systems
        self.apps = apps

    def generate(self) -> str:
        """
        Generate complete config YAML content.

        Returns:
            str: Complete YAML configuration content
        """
        sections = []

        # Header
        sections.append(self._generate_header())

        # Scheduler templates (only those needed)
        sections.append(self._generate_schedulers())

        # Scheduler options documentation
        sections.append(self._generate_sched_opts_section())

        # System configs
        sections.append(self._generate_systems())

        # App configs
        sections.append(self._generate_apps())

        # Custom apps placeholder
        sections.append(self._generate_custom_apps_section())

        # Footer with MPI reference
        sections.append(self._generate_footer())

        return "\n".join(sections)

    def _generate_header(self) -> str:
        """Generate config file header."""
        systems_str = ", ".join(self.systems)
        apps_str = ", ".join(self.apps)

        return f'''# ---------------------------------------------------------------------------
# ParslBox Configuration
# Auto-generated by: pbx config
# Systems: {systems_str}
# Apps: {apps_str}
# ---------------------------------------------------------------------------
'''

    def _generate_schedulers(self) -> str:
        """Generate scheduler templates based on selected systems."""
        schedulers_needed = set()

        for sys_name in self.systems:
            try:
                sys_config = get_system_config(sys_name)
                schedulers_needed.add(sys_config.SCHEDULER.upper())
            except ValueError:
                pass

        output = "# Scheduler submission templates\nschedulers:\n"

        if "PBS" in schedulers_needed:
            output += PBS_TEMPLATE

        if "SLURM" in schedulers_needed:
            output += SLURM_TEMPLATE

        return output + "\n"

    def _generate_sched_opts_section(self) -> str:
        """Generate scheduler options documentation block."""
        return SCHED_OPTS_NOTES

    def _generate_systems(self) -> str:
        """Generate system-specific configuration sections."""
        output = "# ---------------------------------------------------------------------------\n"
        output += "# System-specific configurations\n"
        output += "# ---------------------------------------------------------------------------\n\n"

        for sys_name in self.systems:
            try:
                sys_config = get_system_config(sys_name)
                mpi_defaults = sys_config.get_default_mpi_config_yaml()

                output += f"{sys_name}:\n"
                output += "  pbx_python_env_setup: |\n"
                output += "    # Add your module load and conda activate commands here\n"
                output += "    # Example:\n"
                output += "    # module load conda\n"
                output += "    # conda activate your_env\n"

                # sched_opts — from system defaults or example
                default_sched_opts = sys_config.get_default_sched_opts()
                if default_sched_opts:
                    output += "  sched_opts: |\n"
                    for sched_line in default_sched_opts.strip().split('\n'):
                        output += f"    {sched_line.strip()}\n"
                else:
                    scheduler = sys_config.SCHEDULER.upper()
                    output += "  # sched_opts: |\n"
                    if scheduler == "PBS":
                        output += "  #   #PBS -l filesystems=home:eagle\n"
                        output += "  #   #PBS -l place=scatter\n"
                    else:
                        output += "  #   #SBATCH --mem=128G\n"
                        output += "  #   #SBATCH --gres=gpu:4\n"

                output += "  mpi:\n"

                # Generate MPI config with comments
                output += self._format_mpi_config(mpi_defaults)

                output += "\n"
            except ValueError:
                # System not found, skip
                pass

        return output

    def _format_mpi_config(self, mpi_config: Dict[str, Any]) -> str:
        """
        Format MPI config dict as YAML with comments.

        Shows ALL available options (commented if not set) so users know what's available.
        """
        output = ""

        # Backend (always present)
        backend = mpi_config.get("backend", "openmpi")
        output += f"    backend: {backend}\n"

        # env_setup (empty with guiding comments)
        output += "    env_setup: |              # Shell commands to make MPI available\n"
        output += "      # module load openmpi   # (runs before app's environment_setup)\n"

        # use_gpu_wrapper
        if mpi_config.get("use_gpu_wrapper"):
            output += "    use_gpu_wrapper: true      # Generate per-rank GPU assignment wrapper\n"
        else:
            output += "    # use_gpu_wrapper: false   # Generate per-rank GPU assignment wrapper\n"

        # use_hostlist
        if mpi_config.get("use_hostlist"):
            output += "    use_hostlist: true         # Explicitly pass hostlist to MPI\n"
        else:
            output += "    # use_hostlist: false      # Explicitly pass hostlist to MPI\n"

        # use_short_hostnames
        if mpi_config.get("use_short_hostnames"):
            output += "    use_short_hostnames: true  # Strip domain from hostnames\n"
        else:
            output += "    # use_short_hostnames: false  # Strip domain from hostnames\n"

        # cpu_bind_method
        cpu_bind = mpi_config.get("cpu_bind_method", "none")
        if cpu_bind and cpu_bind != "none":
            output += f"    cpu_bind_method: {cpu_bind}     # Options: none, rankfile, list, depth, depth <N>\n"
        else:
            output += "    # cpu_bind_method: none    # Options: none, rankfile, list, depth, depth <N>\n"

        # add
        add_list = mpi_config.get("add")
        if add_list:
            output += f"    add: {add_list}\n"
        else:
            output += "    # add: []                  # Additional MPI flags to append\n"

        # disable
        disable_list = mpi_config.get("disable")
        if disable_list:
            output += f"    disable: {disable_list}\n"
        else:
            output += "    # disable: []              # MPI flags to remove\n"

        return output

    def _generate_custom_apps_section(self) -> str:
        """Generate custom apps registration placeholder."""
        return CUSTOM_APPS_NOTES

    def _generate_apps(self) -> str:
        """Generate application configuration sections."""
        output = "# ---------------------------------------------------------------------------\n"
        output += "# Application configurations\n"
        output += "# ---------------------------------------------------------------------------\n\n"

        # Add example app config template first
        output += self._generate_example_app_template()

        # Add selected apps
        for app_name in self.apps:
            output += f"{app_name}:\n"

            for sys_name in self.systems:
                output += f"  {sys_name}:\n"

                # App-specific content
                if app_name == "python":
                    # Python app doesn't need executable_path
                    output += "    # Python app uses the Python interpreter from environment\n"
                elif app_name == "julia":
                    # Julia app doesn't need executable_path
                    output += "    # Julia app uses the Julia interpreter from environment\n"
                    output += "    # Set JULIA_PROJECT in environment_setup or env_file to activate a project\n"
                else:
                    output += f"    executable_path: \"/path/to/your/{app_name}/executable/on/{sys_name}\"\n"

                output += "    environment_setup: |\n"
                output += "      # Start with purge & restore so worker subprocesses\n"
                output += "      # get a clean module environment (avoids subtle errors).\n"
                output += "      module purge\n"
                output += "      module restore\n"
                output += "      # Add app-specific environment setup below\n"
                output += "      # module load ...\n"
                output += "    # Optional: Override system MPI settings for this app\n"
                output += "    # mpi:\n"
                output += "    #   cpu_bind_method: rankfile\n"
                output += "\n"

        return output

    def _generate_example_app_template(self) -> str:
        """Generate example app configuration template."""
        return EXAMPLE_APP_TEMPLATE

    def _generate_footer(self) -> str:
        """Generate footer with full MPI configuration reference."""
        return MPI_CONFIG_NOTES


def get_builtin_apps() -> List[str]:
    """Get list of built-in application names."""
    return list(APP_FACTORY.keys())
