"""
Config Generator for ParslBox

This module provides functionality to generate curated config.yaml files
based on user-selected systems and applications.

Used by 'pbx config' command to create minimal, relevant configurations.
"""

from typing import List, Dict, Any
from parslbox.system_configs.loader import get_system_config, get_available_systems
from parslbox.apps.app_registry import APP_FACTORY


# Scheduler templates
PBS_TEMPLATE = '''  pbs:
    template: |
      #!/bin/bash
      #PBS -N {job_name}
      #PBS -q {queue}
      #PBS -l select={select}
      #PBS -l walltime={walltime}
      #PBS -l filesystems={filesystems}
      #PBS -A {project}
      #PBS -o pbx_scheduler.out
      #PBS -j oe
      #PBS -m be
      #PBS -M your@email.com
      
      cd $PBS_O_WORKDIR
      > pbx_scheduler.out
      
      NNODES=$(wc -l < $PBS_NODEFILE)
      echo "NNODES = $NNODES"
      echo "Job ID: $PBS_JOBID"
      echo "Job Name: $PBS_JOBNAME"
      
      {pbx_python_env_setup}
      
      # Set ParslBox environment variables if provided
      {pbx_env_vars}
      
      pbx run --config {config} --run-dir {run_dir} {run_options}
'''

SLURM_TEMPLATE = '''  slurm:
    template: |
      #!/bin/bash
      #SBATCH --job-name={job_name}
      #SBATCH --partition={queue}
      #SBATCH --nodes={select}
      #SBATCH --time={walltime}
      #SBATCH --account={project}
      #SBATCH --output=pbx_scheduler.out
      #SBATCH --error=pbx_scheduler.out
      
      > pbx_scheduler.out
      
      echo "NNODES = $SLURM_JOB_NUM_NODES"
      echo "Job ID: $SLURM_JOB_ID"
      echo "Job Name: $SLURM_JOB_NAME"
      
      {pbx_python_env_setup}
      
      # Set ParslBox environment variables if provided
      {pbx_env_vars}
      
      pbx run --config {config} --run-dir {run_dir} {run_options}
'''


class ConfigGenerator:
    """
    Generates curated ParslBox configuration files.
    
    Args:
        systems: List of system names to include
        apps: List of application names to include
    """
    
    def __init__(self, systems: List[str], apps: List[str]):
        self.systems = systems
        self.apps = apps
    
    def generate(self) -> str:
        """
        Generate complete config YAML content.
        
        Returns:
            str: Complete YAML configuration content
        """
        sections = []
        
        # Header
        sections.append(self._generate_header())
        
        # Scheduler templates (only those needed)
        sections.append(self._generate_schedulers())
        
        # System configs
        sections.append(self._generate_systems())
        
        # Custom apps placeholder
        sections.append(self._generate_custom_apps_section())
        
        # App configs
        sections.append(self._generate_apps())
        
        # Footer with instructions
        sections.append(self._generate_footer())
        
        return "\n".join(sections)
    
    def _generate_header(self) -> str:
        """Generate config file header."""
        systems_str = ", ".join(self.systems)
        apps_str = ", ".join(self.apps)
        
        return f'''# ---------------------------------------------------------------------------
# ParslBox Configuration
# Auto-generated by: pbx config
# Systems: {systems_str}
# Apps: {apps_str}
# ---------------------------------------------------------------------------
'''
    
    def _generate_schedulers(self) -> str:
        """Generate scheduler templates based on selected systems."""
        schedulers_needed = set()
        
        for sys_name in self.systems:
            try:
                sys_config = get_system_config(sys_name)
                schedulers_needed.add(sys_config.SCHEDULER.upper())
            except ValueError:
                pass
        
        output = "# Scheduler submission templates\nschedulers:\n"
        
        if "PBS" in schedulers_needed:
            output += PBS_TEMPLATE
        
        if "SLURM" in schedulers_needed:
            output += SLURM_TEMPLATE
        
        return output + "\n"
    
    def _generate_systems(self) -> str:
        """Generate system-specific configuration sections."""
        output = "# ---------------------------------------------------------------------------\n"
        output += "# System-specific configurations\n"
        output += "# ---------------------------------------------------------------------------\n\n"
        
        for sys_name in self.systems:
            try:
                sys_config = get_system_config(sys_name)
                mpi_defaults = sys_config.get_default_mpi_config_yaml()
                
                output += f"{sys_name}:\n"
                output += "  pbx_python_env_setup: |\n"
                output += "    # Add your module load and conda activate commands here\n"
                output += "    # Example:\n"
                output += "    # module load conda\n"
                output += "    # conda activate your_env\n"
                output += "  mpi:\n"
                
                # Generate MPI config with comments
                output += self._format_mpi_config(mpi_defaults)
                
                output += "\n"
            except ValueError:
                # System not found, skip
                pass
        
        return output
    
    def _format_mpi_config(self, mpi_config: Dict[str, Any]) -> str:
        """
        Format MPI config dict as YAML with comments.
        
        Shows ALL available options (commented if not set) so users know what's available.
        """
        output = ""
        
        # Backend (always present)
        backend = mpi_config.get("backend", "openmpi")
        output += f"    backend: {backend}\n"
        
        # use_gpu_wrapper
        if mpi_config.get("use_gpu_wrapper"):
            output += "    use_gpu_wrapper: true      # Generate per-rank GPU assignment wrapper\n"
        else:
            output += "    # use_gpu_wrapper: false   # Generate per-rank GPU assignment wrapper\n"
        
        # use_hostlist
        if mpi_config.get("use_hostlist"):
            output += "    use_hostlist: true         # Explicitly pass hostlist to MPI\n"
        else:
            output += "    # use_hostlist: false      # Explicitly pass hostlist to MPI\n"
        
        # use_short_hostnames
        if mpi_config.get("use_short_hostnames"):
            output += "    use_short_hostnames: true  # Strip domain from hostnames\n"
        else:
            output += "    # use_short_hostnames: false  # Strip domain from hostnames\n"
        
        # cpu_bind_method
        cpu_bind = mpi_config.get("cpu_bind_method", "none")
        if cpu_bind and cpu_bind != "none":
            output += f"    cpu_bind_method: {cpu_bind}     # Options: none, rankfile, list, depth, depth <N>\n"
        else:
            output += "    # cpu_bind_method: none    # Options: none, rankfile, list, depth, depth <N>\n"
        
        # add
        add_list = mpi_config.get("add")
        if add_list:
            output += f"    add: {add_list}\n"
        else:
            output += "    # add: []                  # Additional MPI flags to append\n"
        
        # disable
        disable_list = mpi_config.get("disable")
        if disable_list:
            output += f"    disable: {disable_list}\n"
        else:
            output += "    # disable: []              # MPI flags to remove\n"
        
        return output
    
    def _generate_custom_apps_section(self) -> str:
        """Generate custom apps registration placeholder."""
        return '''# ---------------------------------------------------------------------------
# Custom Application Registration
#
# Register your own custom applications here. Once registered, they work
# just like built-in apps (lammps, vasp, python).
#
# Example:
# custom_apps:
#   my_app:
#     module: "/path/to/my_app.py"
#     class: "MyApp"
# ---------------------------------------------------------------------------

custom_apps: {}

'''
    
    def _generate_apps(self) -> str:
        """Generate application configuration sections."""
        output = "# ---------------------------------------------------------------------------\n"
        output += "# Application configurations\n"
        output += "# ---------------------------------------------------------------------------\n\n"
        
        # Add example app config template first
        output += self._generate_example_app_template()
        
        # Add selected apps
        for app_name in self.apps:
            output += f"{app_name}:\n"
            
            for sys_name in self.systems:
                output += f"  {sys_name}:\n"
                
                # App-specific content
                if app_name == "python":
                    # Python app doesn't need executable_path
                    output += "    # Python app uses the Python interpreter from environment\n"
                else:
                    output += f"    executable_path: \"/path/to/your/{app_name}/executable/on/{sys_name}\"\n"
                
                output += "    environment_setup: |\n"
                output += "      # Add app-specific environment setup here\n"
                output += "      # module purge\n"
                output += "      # module load ...\n"
                output += "    # Optional: Override system MPI settings for this app\n"
                output += "    # mpi:\n"
                output += "    #   cpu_bind_method: rankfile\n"
                output += "\n"
        
        return output
    
    def _generate_example_app_template(self) -> str:
        """Generate example app configuration template."""
        return '''#===== Example APP Template =====#
# Copy this template to add your own applications

# app_name:  # e.g., lammps, vasp, my_simulation
#   system_name:  # e.g., polaris, aurora-tile, sophia
#     # Full, absolute path to the software executable on the system.
#     executable_path: "/path/to/your/software/executable/on/system"
# 
#     # Shell commands to set up the environment on a compute node.
#     # This block will be executed before the main mpirun command.
#     # Use '|' to define a multi-line string in YAML.
#     environment_setup: |
#       # Add all necessary `module load` and `export` commands here.
#       # Example:
#       # module purge      # Always purge modules first in apps
#       # module restore    # Then restore modules if you want
#       # module load PrgEnv-gnu
#       # module load ...
# 
#     # Optional: Override system MPI settings for this app
#     # mpi:
#     #   cpu_bind_method: rankfile
#     #   use_gpu_wrapper: true

# ============================================

'''
    
    def _generate_footer(self) -> str:
        """Generate helpful footer instructions."""
        return '''# ---------------------------------------------------------------------------
# Additional Information
# ---------------------------------------------------------------------------
#
# MPI Configuration Options:
#   backend: openmpi | pals | srun
#   mpi_cmd: Custom MPI command path (optional)
#   use_gpu_wrapper: true | false
#   use_hostlist: true | false
#   use_short_hostnames: true | false
#   cpu_bind_method: none | rankfile | list | depth | depth <N>
#   add: ["--flag1", "--flag2"]  # Flags to append
#   disable: ["--flag"]          # Flags to remove
#
# Template Variables (for use in 'add'):
#   {total_ranks}, {ranks_per_node}, {cores_per_rank}
#   {hostlist}, {rankfile_path}, {wrapper_path}
#
# To add more applications, copy the structure above and customize.
# See documentation: https://github.com/your-org/parslbox
'''


def get_builtin_apps() -> List[str]:
    """Get list of built-in application names."""
    return list(APP_FACTORY.keys())
